name: Approval

on:
  pull_request:
    types: [opened, synchronize]

env:
  BRANCH: ${{ github.base_ref }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  token: ${{ vars.ACTION_GITHUB_TOKEN }}

jobs:
  check-approvers:
    name: Check Approvers
    runs-on: ubuntu-latest
    steps:
      - name: Display Required Approvers
        run: |
          echo 2222
