name: Clone

on:
  push:
  pull_request_target:
    branches: [ "main" ]

permissions: write-all

jobs:
  Clone:
    runs-on: ubuntu-latest
    env:
      PR_ID: ${{ github.event.pull_request.number }}
      COMMIT_ID: ${{ github.event.pull_request.head.sha }}
      BRANCH: develop
    steps:
    - name: Clone paddle
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 1000

    - name: Push paddle-action.tar.gz to bos
      env:
        A: ${{ secrets.A }}
      run: |
        echo "h"

    - name: Scheduling other workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh workflow run Scheduling -f PR_ID=${PR_ID} COMMIT_ID=${COMMIT_ID}
