name: Clone

on:
  push:
  pull_request_target:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  Clone:
    runs-on: ubuntu-latest
    env:
      PR_ID: ${{ github.event.pull_request.number }}
      COMMIT_ID: ${{ github.event.pull_request.head.sha }}
      BRANCH: develop
    steps:
    - name: Clone paddle
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 1000

    - name: Push paddle-action.tar.gz to bos
      env:
        A: ${{ secrets.A }}
      run: |
        echo "h"

    - name: Scheduling other workflow
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/PR-CI-Scheduling.yml/dispatches \
          -d '{"ref": "main"}'
