name: Re-run

on:
  issue_comment:
    types: [created]

jobs:
  re-run:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/re-run') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Convert comment to lowercase
        id: convert
        run: |
          echo ${{ github.event.comment.user.login }}
          echo ${{ github.event.issue.user.login }}
          comment_body=$(echo '${{ github.event.comment.body }}' | tr '[:upper:]' '[:lower:]')
          echo $comment_body
          echo "comment_body=$comment_body" >> $GITHUB_ENV

      - name: Rerun Workflow
        if: ${{ contains(env.comment_body, 'all-failed') }}
        uses: ./.github/actions/rerun-workflow
        with:
          PR_ID: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          JOB_NAME: 'all-failed'
    
      - name: Rerun Workflow
        if: ${{ contains(env.comment_body, 'job-single') }}
        uses: ./.github/actions/rerun-workflow
        with:
          PR_ID: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          JOB_NAME: 'job-single'

      - name: Rerun Workflow
        if: ${{ contains(env.comment_body, 'job1') }}
        uses: ./.github/actions/rerun-workflow
        with:
          PR_ID: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          JOB_NAME: 'job1 / job1-in'
        
      - name: Rerun Workflow
        if: ${{ contains(env.comment_body, 'job2') }}
        uses: ./.github/actions/rerun-workflow
        with:
          PR_ID: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          JOB_NAME: 'job2'
