name: test_name

on: 
  pull_request:
    branches:
    - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: h
      run: |
        echo "im test_file in origin ${{ secrets.a }}"
