name: test-call

on:
  workflow_call:
    inputs:
      PR_ID:
        description: 'PR number'
        required: true
        type: string
      COMMIT_ID:
        description: 'commit number'
        required: true
        type: string

jobs:
  test-call:
    runs-on: ubuntu-latest
    env:
      A: ${{ secrets.A }}
    steps:    
    - name: test-call
      run: |
        echo "test call"
