name: single

on:
  pull_request:
    types: [opened, synchronize]

permissions: read-all

env:
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OWNER: ${{ github.repository_owner }}
  REPO: ${{ github.event.repository.name }}
  TARGET_WORKFLOW_NAME: test

concurrency:
  group: ${PR_ID}-single
  cancel-in-progress: true

jobs:
  job-single:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: job-single
      run: |
        echo "job-single"
        sleep 20
        exit 1
