name: work1

on:
  workflow_call:

env:
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  ci_scripts: ${{ github.workspace }}/ci

defaults:
  run:
    shell: bash

jobs:
  job1-in:
    runs-on: ubuntu-latest
    steps:
      - name: job1-in
        run: |
          echo "job1-in"
          sleep 20
          exit 0
